/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ApiPublicMembershipRouteImport } from './routes/api/public/membership'
import { Route as ApiPublicMembershipRestoreRouteImport } from './routes/api/public/membership.restore'
import { Route as ApiPublicPaddleConfigRouteImport } from './routes/api/public/paddle/config'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembershipRoute = ApiPublicMembershipRouteImport.update({
  id: '/api/public/membership',
  path: '/api/public/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembershipRestoreRoute =
  ApiPublicMembershipRestoreRouteImport.update({
    id: '/restore',
    path: '/restore',
    getParentRoute: () => ApiPublicMembershipRoute,
  } as any)
const ApiPublicPaddleConfigRoute = ApiPublicPaddleConfigRouteImport.update({
  id: '/api/public/paddle/config',
  path: '/api/public/paddle/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle/webhook',
  path: '/api/public/paddle/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/payment': typeof PaymentRoute
  '/api/public/membership': typeof ApiPublicMembershipRouteWithChildren
  '/api/public/membership/restore': typeof ApiPublicMembershipRestoreRoute
  '/api/public/paddle/config': typeof ApiPublicPaddleConfigRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/payment': typeof PaymentRoute
  '/api/public/membership': typeof ApiPublicMembershipRouteWithChildren
  '/api/public/membership/restore': typeof ApiPublicMembershipRestoreRoute
  '/api/public/paddle/config': typeof ApiPublicPaddleConfigRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/payment': typeof PaymentRoute
  '/api/public/membership': typeof ApiPublicMembershipRouteWithChildren
  '/api/public/membership/restore': typeof ApiPublicMembershipRestoreRoute
  '/api/public/paddle/config': typeof ApiPublicPaddleConfigRoute
  '/api/public/paddle/webhook': typeof ApiPublicPaddleWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/payment'
    | '/api/public/membership'
    | '/api/public/membership/restore'
    | '/api/public/paddle/config'
    | '/api/public/paddle/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/payment'
    | '/api/public/membership'
    | '/api/public/membership/restore'
    | '/api/public/paddle/config'
    | '/api/public/paddle/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/payment'
    | '/api/public/membership'
    | '/api/public/membership/restore'
    | '/api/public/paddle/config'
    | '/api/public/paddle/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  PaymentRoute: typeof PaymentRoute
  ApiPublicMembershipRoute: typeof ApiPublicMembershipRouteWithChildren
  ApiPublicPaddleConfigRoute: typeof ApiPublicPaddleConfigRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership': {
      id: '/api/public/membership'
      path: '/api/public/membership'
      fullPath: '/api/public/membership'
      preLoaderRoute: typeof ApiPublicMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership/restore': {
      id: '/api/public/membership/restore'
      path: '/restore'
      fullPath: '/api/public/membership/restore'
      preLoaderRoute: typeof ApiPublicMembershipRestoreRouteImport
      parentRoute: typeof ApiPublicMembershipRoute
    }
    '/api/public/paddle/config': {
      id: '/api/public/paddle/config'
      path: '/api/public/paddle/config'
      fullPath: '/api/public/paddle/config'
      preLoaderRoute: typeof ApiPublicPaddleConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paddle/webhook': {
      id: '/api/public/paddle/webhook'
      path: '/api/public/paddle/webhook'
      fullPath: '/api/public/paddle/webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicMembershipRouteChildren {
  ApiPublicMembershipRestoreRoute: typeof ApiPublicMembershipRestoreRoute
}

const ApiPublicMembershipRouteChildren: ApiPublicMembershipRouteChildren = {
  ApiPublicMembershipRestoreRoute: ApiPublicMembershipRestoreRoute,
}

const ApiPublicMembershipRouteWithChildren =
  ApiPublicMembershipRoute._addFileChildren(ApiPublicMembershipRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  PaymentRoute: PaymentRoute,
  ApiPublicMembershipRoute: ApiPublicMembershipRouteWithChildren,
  ApiPublicPaddleConfigRoute: ApiPublicPaddleConfigRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
